int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
int _0f(int,int);
int _1f(int,int);
int _2f(int,int);
int _3f(int,int);
void times_table(void);
int _mo9(int num1);
int add(int, int);
